export type TalkNote = {
  slide: number;
  title: string;
  time: string;
  cue: string;
  cheat: string;
  anchor: string;
  script: string[];
};

export const talkNotes: TalkNote[] = [
  {
    slide: 1,
    title: 'Steering AI With Design Taste',
    time: '0:00',
    cue: 'Let the room read. Resize the copy once, then click both Unslop controls.',
    cheat: 'The presentation is already the first demo. Everything worked before the details, but it did not feel the same.',
    anchor: 'Everything worked without those details. But it would not have felt the same.',
    script: [
      'Hi everyone, I am Adrian. I build interfaces, experiments, and products with AI, but the part I care about most is how they feel in someone\'s hands.',
      'Before I explain anything, look at this title page. I can resize the sentence. The value follows my hand. These separators are intentionally sloppy, and I can fix each one directly.',
      'None of this is necessary for a title slide. It already worked. But these tiny responses change the relationship between me and the interface. That relationship is what this talk is about.',
    ],
  },
  {
    slide: 2,
    title: 'Game feel',
    time: '1:20',
    cue: 'Short setup. Move quickly into the comparison.',
    cheat: 'Games learned early that correctness is not enough. Control has to feel good moment to moment.',
    anchor: 'Games taught us that the feature and the feeling are two different things.',
    script: [
      'The easiest place to see this idea is in games. Game designers have spent decades tuning what happens between an input and the response on screen.',
      'They call it game feel. The game can be technically correct and still feel lifeless. Let me show you.',
    ],
  },
  {
    slide: 3,
    title: 'The plain version',
    time: '1:50',
    cue: 'Let the clip play for a few seconds. Do not over-explain it.',
    cheat: 'It works. Character, keyboard, physics, platforms. Nothing is technically broken.',
    anchor: 'Technically, this works.',
    script: [
      'This version has a character. I can move with the keyboard. There is gravity, collision, and platforms.',
      'If this were a checklist, every requirement could be marked complete. Technically, this works.',
    ],
  },
  {
    slide: 4,
    title: 'The version with feel',
    time: '2:25',
    cue: 'Let the audience notice the difference before naming details.',
    cheat: 'Same task, but movement has anticipation, follow-through, camera response, and personality.',
    anchor: 'The rules did not change. The experience did.',
    script: [
      'Now watch the same basic idea with care added to the response.',
      'The movement has anticipation and follow-through. The camera participates. The character has personality. The rules did not change. The experience did.',
    ],
  },
  {
    slide: 5,
    title: 'Same features, different feel',
    time: '3:00',
    cue: 'Point to the matching checklists, then pause.',
    cheat: 'The checklists are identical. Your hands would never call these the same experience.',
    anchor: 'The checklist says they are the same. Your hands say they are not.',
    script: [
      'This is the important comparison. Both have a character, keyboard navigation, physics, and platforms. The feature list is identical.',
      'But nobody playing these would describe them as the same experience. The checklist says they are the same. Your hands say they are not.',
      'That gap between functional and satisfying is where design engineering lives.',
    ],
  },
  {
    slide: 6,
    title: 'Interaction feel',
    time: '4:00',
    cue: 'Give the definition slowly.',
    cheat: 'Interaction feel applies game-feel thinking to ordinary product interfaces.',
    anchor: 'Interaction feel is game feel for everyday product interfaces.',
    script: [
      'I use the term interaction feel for this. It is the application of game-feel principles to everyday product interfaces.',
      'Instead of asking only, does the button work, we also ask: did the action feel acknowledged, continuous, physical, and complete?',
    ],
  },
  {
    slide: 7,
    title: 'Make the app feel alive',
    time: '4:45',
    cue: 'Stress responsive, expressive, and emotionally satisfying.',
    cheat: 'Not animation everywhere. It is a response that makes software feel attentive and alive.',
    anchor: 'The goal is not to make an app animated. The goal is to make it attentive.',
    script: [
      'Interaction feel makes digital interactions more responsive, expressive, and emotionally satisfying.',
      'That does not mean adding animation everywhere. More motion can easily make a product worse. The goal is not to make an app animated. The goal is to make it attentive.',
      'When the response matches the intention, the software starts to feel alive.',
    ],
  },
  {
    slide: 8,
    title: 'Not new',
    time: '5:40',
    cue: 'Reset the room before the historical clips.',
    cheat: 'This is not an AI-era discovery. We have felt it before.',
    anchor: 'We have felt this before.',
    script: [
      'This is not new, and it definitely did not begin with AI.',
      'We have felt this before. Some interactions became so natural that we forgot how surprising they were the first time.',
    ],
  },
  {
    slide: 9,
    title: 'The original iPhone scroll',
    time: '6:05',
    cue: 'Play the clip and let the crowd reaction inside it do the work.',
    cheat: 'The feature was a list. The breakthrough was how it responded to a finger.',
    anchor: 'Today this needs no explanation. In 2007, it made a room erupt.',
    script: [
      'Today, this gesture needs no explanation. In 2007, it made a room erupt.',
      'The feature was a contact list. Scrolling was not new. The breakthrough was the direct relationship between the finger, the movement, the momentum, and the edge of the content.',
      'We call it obvious now because someone cared enough to make it feel obvious.',
    ],
  },
  {
    slide: 10,
    title: 'Software as responsive material',
    time: '7:15',
    cue: 'Keep the Apple history short. Use it as lineage, not as a product review.',
    cheat: 'Apple kept treating software like material that responds to movement and context.',
    anchor: 'Great interaction work makes abstract software feel physical enough to understand.',
    script: [
      'Apple kept investing in this idea: software can behave like a responsive material. Controls flex, layers communicate depth, and movement explains where things came from.',
      'Whether we like every visual trend is not the point. The useful lesson is that hardware, graphics, design, and engineering are considered together.',
      'Great interaction work makes abstract software feel physical enough to understand.',
    ],
  },
  {
    slide: 11,
    title: 'The sum of three disciplines',
    time: '8:10',
    cue: 'Name the three ingredients, then transition to the demos.',
    cheat: 'Design, motion, and engineering compound. None of them creates interaction feel alone.',
    anchor: 'Interaction feel is the compound result of design, motion, and engineering.',
    script: [
      'Interaction feel is not just beautiful design. It is not just good motion. It is not just precise engineering.',
      'It is the compound result of all three. Design creates the intention. Motion communicates change. Engineering makes the response immediate, continuous, and reliable.',
      'Now I want to show what that looks like in the way I work with AI.',
    ],
  },
  {
    slide: 12,
    title: 'Demo',
    time: '9:00',
    cue: 'Brief pause. This begins the Keeby section.',
    cheat: 'First demo: turning a normal settings control into something playable.',
    anchor: 'Let us start with a very ordinary control.',
    script: ['Let us start with a very ordinary control inside Keeby.'],
  },
  {
    slide: 13,
    title: 'A tone control, but playable',
    time: '9:15',
    cue: 'Introduce Keeby only as context, not as a product pitch.',
    cheat: 'Keeby plays mechanical keyboard sounds. Tone normally looks like sliders, but the model is really two-dimensional.',
    anchor: 'If the model is two-dimensional, the control should let you think in two dimensions.',
    script: [
      'Keeby is my app that makes typing sound and feel like a mechanical keyboard. Users can tune the tone of different actions.',
      'The safe version of this setting would be a pair of sliders. It would work, but the mental model is really two-dimensional. One direction changes brightness, the other changes body.',
      'If the model is two-dimensional, the control should let you think in two dimensions. So I turned the setting into a tone pad you can play.',
    ],
  },
  {
    slide: 14,
    title: 'Tone pad in the macOS app',
    time: '10:05',
    cue: 'Let the video loop. Point out direct manipulation and visual response.',
    cheat: 'The control previews the sound while the point follows the hand. The setting becomes an instrument.',
    anchor: 'The setting stops feeling like configuration and starts feeling like an instrument.',
    script: [
      'This is the control in the actual macOS app. I can move directly through the sound space, and every change is visible and audible immediately.',
      'The setting stops feeling like configuration and starts feeling like an instrument. The feature is still tone adjustment. The relationship with it is completely different.',
    ],
  },
  {
    slide: 15,
    title: 'Build the interaction in layers',
    time: '11:00',
    cue: 'Walk left to right. Spend the most time on stages 3, 4, and Don\'t do.',
    cheat: 'Body, interaction, feel, feedback, restraint. Mention smooth following, press scale, circles, haptics, ticking, and sound thresholds.',
    anchor: 'Design engineering is not only adding delight. It is also knowing where delight needs restraint.',
    script: [
      'I did not ask AI to make the final interaction in one shot. I built it in layers so every problem was visible.',
      'Stage one is only the body. Get the layout and proportions right before behavior makes the screen harder to judge. Stage two adds direct interaction and grid snapping.',
      'Stage three creates the feel. The point does not teleport to the cursor. It follows with a smooth interpolation. Pressing scales the main knob with a quick response and a softer release. The surrounding circles grow to make the current value legible.',
      'Stage four adds feedback. There is haptic feedback at meaningful changes, and a ticking sound as the point crosses the grid. The sound is part of the spatial model, not decoration.',
      'Then the last panel is the warning. Without a threshold, every tiny movement makes sound. It becomes overwhelming immediately. Design engineering is not only good design and smooth animation. It is also knowing where delight needs restraint.',
    ],
  },
  {
    slide: 16,
    title: 'Demo',
    time: '13:20',
    cue: 'Reset. Move into the Golden Ticket experiment.',
    cheat: 'Second demo: communicating physical motion to AI.',
    anchor: 'The next problem was not a control. It was a motion I could feel but could not explain cleanly.',
    script: ['The next problem was not a control. It was a motion I could feel in my head but could not explain cleanly with words.'],
  },
  {
    slide: 17,
    title: 'RSVP but Golden Ticket',
    time: '13:40',
    cue: 'Give the idea in one sentence.',
    cheat: 'I wanted RSVP to feel like receiving an invitation, not submitting a form.',
    anchor: 'I wanted RSVP to feel less like submitting a form and more like receiving an invitation.',
    script: [
      'The idea was simple: RSVP, but the Polar Express golden ticket.',
      'I wanted RSVP to feel less like submitting a form and more like receiving an invitation. That emotional goal became the direction for the whole interaction.',
    ],
  },
  {
    slide: 18,
    title: 'The finished Golden Ticket',
    time: '14:15',
    cue: 'Let the video play first. Step away from the screen.',
    cheat: 'Result first. Ticket falls in, responds like metal, and the punch becomes the confirmation.',
    anchor: 'Show the memorable result before explaining the machinery.',
    script: [
      'This is the finished version. I am going to let it play once before explaining it.',
      'The ticket falls into the scene, catches the light, responds to movement, and the single-hole puncher becomes the confirmation action.',
      'I like showing the result first because the audience should understand the feeling before seeing the machinery.',
    ],
  },
  {
    slide: 19,
    title: 'From image to physical gold',
    time: '15:15',
    cue: 'Move the cursor so the light travels across the physical material. Point to each map.',
    cheat: 'AI-generated artwork became albedo, normal, roughness, and metalness maps. Moving light reveals the difference.',
    anchor: 'A flat image describes color. A material describes how the surface responds to light.',
    script: [
      'The starting point was an AI-generated image. On the left it is simply pixels. It already looks gold, but it does not behave like gold.',
      'On the right, the same artwork becomes a physical material. I derived an albedo map for color, a normal map for surface relief, a roughness map for how sharply light reflects, and full metalness.',
      'Watch what happens when the light moves. The artwork now reacts instead of only looking metallic. A flat image describes color. A material describes how the surface responds to light.',
    ],
  },
  {
    slide: 20,
    title: 'Steering the fall',
    time: '16:45',
    cue: 'Compare all three loops. Click the Figma reference and close it after the explanation.',
    cheat: 'Straight drop, cursor response, curved fall. The Figma side view made the spatial intention explicit to AI.',
    anchor: 'If the intention is spatial, communicate it spatially.',
    script: [
      'Here are three stages running together. The first is a straight drop. It technically enters, but it feels flat. The second adds cursor response so the ticket and reflections move together.',
      'The third adds the curved fall. This was the difficult part to communicate. Saying slide down smoothly was too vague. I wanted it to begin slightly behind, bend forward during the descent, and finish at its original depth.',
      'So I drew the front, side, and back views in Figma. Then I copied the frame as SVG and pasted it into AI. The SVG gave the model exact geometry, labels, and spatial relationships.',
      'The diagram was not documentation after the work. It was part of the prompt. If the intention is spatial, communicate it spatially.',
    ],
  },
  {
    slide: 21,
    title: 'Demo',
    time: '18:40',
    cue: 'Reset for the Etch A Sketch experiment.',
    cheat: 'Third demo: a strange association becomes a memorable interface.',
    anchor: 'Now for the experiment that connected interaction feel to distribution.',
    script: ['Now for the experiment that connected interaction feel to distribution.'],
  },
  {
    slide: 22,
    title: 'E-signature but Etch A Sketch',
    time: '18:55',
    cue: 'Keep the setup playful and brief.',
    cheat: 'An ordinary signature field turned into a toy everyone immediately understands.',
    anchor: 'A familiar object can teach an unusual interaction without instructions.',
    script: [
      'The prompt was almost a joke: an e-signature field, but Etch A Sketch.',
      'A normal signature field is forgettable. The toy gives us two knobs, a drawing surface, physical constraints, and a shake-to-clear behavior that people already understand.',
      'A familiar object can teach an unusual interaction without instructions.',
    ],
  },
  {
    slide: 23,
    title: 'The Etch A Sketch demo',
    time: '19:30',
    cue: 'Let the video show the knobs and clearing gesture.',
    cheat: 'Result first. Watch the constraint create personality instead of friction.',
    anchor: 'The constraint is the personality.',
    script: [
      'The two knobs control the line exactly like the toy. It is slower than drawing with a mouse, and that is the point.',
      'Usually we remove friction. Here the constraint is the personality. It turns signing into a small performance, which makes the result worth showing to someone else.',
    ],
  },
  {
    slide: 24,
    title: 'The public response',
    time: '20:20',
    cue: 'Point to the view count. Do not make it a victory lap.',
    cheat: 'The clip reached about 895K views. The demonstration communicated itself in seconds.',
    anchor: 'Interesting interactions are naturally demonstrable, and demonstrable work travels.',
    script: [
      'I posted the experiment publicly, and it reached about eight hundred ninety-five thousand views.',
      'The important part is not the number by itself. It is why the clip was easy to share. You can understand the idea in a few seconds, even without knowing the implementation.',
      'Interesting interactions are naturally demonstrable, and demonstrable work travels.',
    ],
  },
  {
    slide: 25,
    title: 'SVG as an explicit visual prompt',
    time: '21:15',
    cue: 'Move from Figma on the left to the implemented Keeby result on the right.',
    cheat: 'Copy the exact Figma frame as SVG. AI receives geometry instead of guessing from prose.',
    anchor: 'I do not only prompt AI with words. I give it artifacts it can reason from.',
    script: [
      'The same principle applies to static layout. I designed the Keeby Notch overlay in Figma, selected the exact frame, and copied it as SVG.',
      'I pasted that SVG into AI. Now the model had the actual paths, dimensions, corners, and hierarchy. The geometry stopped being open to interpretation.',
      'I do not only prompt AI with words. I give it artifacts it can reason from. A sketch, screenshot, or SVG can be a better prompt than another paragraph.',
    ],
  },
  {
    slide: 26,
    title: 'React Grab',
    time: '22:30',
    cue: 'Let the recording demonstrate the workflow. Credit Aidan Bai by name.',
    cheat: 'React Grab by Aidan Bai copies the exact element and component context into AI.',
    anchor: 'Point at the thing instead of describing the neighborhood.',
    script: [
      'When the interface is already running, I use React Grab, made by Aidan Bai.',
      'I point at the exact element that feels wrong, copy it, and paste its component context into AI. I do not need a long explanation of where the element lives or which file might own it.',
      'The moment I notice something feels wrong, I want the distance between noticing and editing to be almost zero. Point at the thing instead of describing the neighborhood.',
    ],
  },
  {
    slide: 27,
    title: 'The system is public',
    time: '23:40',
    cue: 'Invite the audience to scan. Mention that the repo includes the deck and design skills.',
    cheat: 'The repository is public. The QR opens the live deck. Skills encode reusable design and motion judgment for AI.',
    anchor: 'The tools can change. The loop stays the same: make the intention visible, build it, feel it, refine it.',
    script: [
      'Everything behind this talk is public. The QR opens the live deck, and the GitHub repository includes the presentation and the skills I use to give AI a stronger design and motion vocabulary.',
      'These skills do not replace judgment. They make judgment reusable. They remind the agent about restraint, direct manipulation, easing, feedback, reduced motion, and the quality bar I want it to apply.',
      'The tools can change. The loop stays the same: make the intention visible, build it, feel it, and keep refining it.',
    ],
  },
  {
    slide: 28,
    title: 'Keeby as evidence',
    time: '25:00',
    cue: 'Treat the numbers as evidence of the process, not the topic of the talk.',
    cheat: 'Building in public helped Keeby reach #1 Top Paid, 1K+ users, and $6K+ in one month.',
    anchor: 'Keeby is not the whole story. It is proof that users feel the details.',
    script: [
      'This process did not stay inside experiments. Building Keeby in public became organic distribution.',
      'Keeby reached number one in Top Paid Apps, more than one thousand users, and over six thousand US dollars in a single month.',
      'Keeby is not the whole story. It is proof that users feel the details. Utility gets someone through the door. Feeling gives them a reason to care, and sharing the process gives the work a way to find them.',
    ],
  },
  {
    slide: 29,
    title: 'The process is the marketing',
    time: '26:20',
    cue: 'Slow down. This is the distribution thesis.',
    cheat: 'People share process, not ads. Show the making, decisions, failures, and improvements.',
    anchor: 'Share the process. The process is the marketing.',
    script: [
      'Shipping is not the end of the work. People still need to discover it.',
      'I build in public because people do not share ads. They share process. They share the strange first idea, the rough version, the correction, and the moment it finally feels right.',
      'Organic distribution reveals what resonates. Paid distribution can amplify that later. They are not enemies. First learn what people care about, then help that message travel.',
      'Share the process. The process is the marketing.',
    ],
  },
  {
    slide: 30,
    title: 'Keeby demo',
    time: '27:35',
    cue: 'Let the product breathe. Keep your words minimal.',
    cheat: 'Final proof. Keeby combines utility, visual care, motion, haptics, and sound into one coherent experience.',
    anchor: 'The goal is not a collection of effects. The goal is one coherent experience.',
    script: [
      'I will end the examples with Keeby itself.',
      'What I want you to notice is not one animation or one sound. It is the way utility, visual care, motion, haptics, and audio support the same personality.',
      'The goal is not a collection of effects. The goal is one coherent experience.',
    ],
  },
  {
    slide: 31,
    title: 'Shipping is only half the job',
    time: '28:30',
    cue: 'Finish slowly. Leave the final line on screen.',
    cheat: 'Feature makes it useful. Feeling makes it memorable. Distribution gives it a chance to matter.',
    anchor: 'Make the intention visible, make the interaction feel right, then help the work find its people.',
    script: [
      'AI gives us more attempts than we have ever had before. It can help us turn an idea into an interface incredibly quickly.',
      'But speed alone does not decide what becomes memorable. Taste decides which attempts survive. Care decides how the product responds. Distribution makes sure the work gets a chance.',
      'The feature makes it useful. The feeling makes it memorable. Distribution gives it a chance to matter.',
      'Make the intention visible, make the interaction feel right, then help the work find its people. Thank you.',
    ],
  },
];

export const talkCheckpoints = [
  '05:40 · Slide 8 · Not new',
  '09:00 · Slide 12 · Keeby demo',
  '13:20 · Slide 16 · Golden Ticket demo',
  '18:40 · Slide 21 · Etch A Sketch demo',
  '23:40 · Slide 27 · Public workflow',
  '28:30 · Slide 31 · Close',
];

export const emergencyCuts = [
  'Slide 10: reduce the Apple lineage to one sentence.',
  'Slide 14: let the video speak and use only the anchor line.',
  'Slide 19: name the four maps without explaining each one.',
  'Slide 23: let the Etch A Sketch video run with no extra narration.',
  'Slide 27: say the repository is public, invite the scan, then move on.',
];
